<?php
/**
 *
 * @description Magento Module for Rely Payment
 * @author   Codilar Team Player <ankith@codilar.com>
 * @license  Open Source
 * @link     https://www.codilar.com
 * @copyright Copyright © 2020 Codilar Technologies Pvt. Ltd.. All rights reserved
 *
 */
?>
<?php
/** @var $block Promotion */

use Rely\Payment\Block\Marketing\Catalog\Promotion;

?>

<?php if ($block->isPopUpEnabled()):?>

<div class="rely-popup-container">
    <!--    <button data-modal-target="#rely-popup-modal">Open Modal</button>-->
    <div class="rely-popup-modal" id="rely-popup-modal">
        <div id="rely-popup-overlay"></div>
        <div class="rely-popup-model-container">
            <div class="rely-popup-modal-header">
                <button data-close-button class="close-button">&times;</button>
            </div>
            <div class="rely-popup-modal-body">
                <div class="rely-popup-content">
                    <?php if ($block->getRelyPaymentType()==='rely_instalment'):?>
                        <?= $block->getChildHtml('installment_popup_content')?>
                    <?php else:?>
                        <?= $block->getChildHtml('pay_later_popup_content')?>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </div>

</div>
<?php endif;?>
<script type="text/x-magento-init">
        {
            "*": {
                "Rely_Payment/js/marketing/popup":
                        {
                            "config":
                                     {
                                        "popup_enabled": <?= $block->escapeJs(__($block->isPopUpEnabled()))?>
                                     }
                        }
            }
        }
</script>
