<?php
/**
 *
 * @description Magento Module for Rely Payment
 * @author   Codilar Team Player <ankith@codilar.com>
 * @license  Open Source
 * @link     https://www.codilar.com
 * @copyright Copyright © 2020 Codilar Technologies Pvt. Ltd.. All rights reserved
 *
 */
?>
<span class="main-text">Shop now, play later with</span>
<div class="strip-image">
    <img src="<?=$block->escapeHtml(__($block->getLogo()))?>" alt="rely-logo"/>
    <span class="main-text link" style="text-decoration: underline;">learn more</span>
</div>
