<?php
/**
 *
 * @description Magento Module for Rely Payment
 * @author   Codilar Team Player <ankith@codilar.com>
 * @license  Open Source
 * @link     https://www.codilar.com
 * @copyright Copyright © 2020 Codilar Technologies Pvt. Ltd.. All rights reserved
 *
 */
?>
<div class="strip-widget-content-text" id="click-me">
<?=$block->escapeHtml(__('or Pay in 4 interest-free payment with '))?>
<img src="<?=$block->escapeHtml(__($block->getLogo()));?>" alt="rely logo"/>
<span style="text-decoration: underline;margin-left: 4px;font-weight: 800;">
                    Learn more
                </span>
</div>
